services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
    ports:
      - "9000:9000"
    command: >
      sh -c "composer install && php-fpm"

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php